"""create initial tables

Revision ID: 9d084352e142
Revises: 
Create Date: 2026-09-28 16:31:13.148821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d084352e142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.Enum('website', 'api', name='resourcetype', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('method', sa.Enum('GET', 'HEAD', name='httpmethod', native_enum=False), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('expected_status_code', sa.Integer(), nullable=True),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'up', 'down', 'degraded', name='monitorstatus', native_enum=False), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('recovery_threshold', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monitors_enabled_next_check_at', 'monitors', ['enabled', 'next_check_at'], unique=False)
    op.create_index(op.f('ix_monitors_user_id'), 'monitors', ['user_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='incidentstatus', native_enum=False), nullable=False),
    sa.Column('cause', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_monitor_id'), 'incidents', ['monitor_id'], unique=False)
    op.create_table('monitor_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failure', name='checkstatus', native_enum=False), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_monitor_checks_monitor_checked_at', 'monitor_checks', ['monitor_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_monitor_checks_monitor_id'), 'monitor_checks', ['monitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_checks_monitor_id'), table_name='monitor_checks')
    op.drop_index('ix_monitor_checks_monitor_checked_at', table_name='monitor_checks')
    op.drop_table('monitor_checks')
    op.drop_index(op.f('ix_incidents_monitor_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_monitors_user_id'), table_name='monitors')
    op.drop_index('ix_monitors_enabled_next_check_at', table_name='monitors')
    op.drop_table('monitors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
